services:
  app:
    image: a7188968e04b 
    tty: true
    environment:
      - BASE_URL=https://testcrudstudy.de
      - NODE_ENV=production
      - PORT=58669
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=sundial
    ports:
      - 127.0.0.1:58669:58669
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
  db:
    image: postgres:alpine
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sundial
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_COLLATE=en_US.utf8
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  ui:
    image: 3128f71abf60 
    environment:
      - REACT_APP_SERVER_URL=https://testcrudstudy.de
      - REACT_APP_BASE_URL=https://testcrudstudy.de
    ports:
    - 127.0.0.1:3001:3000
    volumes:
      - ./ui:/app 
    depends_on:
      - app

volumes:
  db-data:
secrets:
  db-password:
    file: ./database/password.txt