export const BASE_URL = window._env_.API_URL || 'http://localhost:58669';
export const GET_JOBS = '/api/monitors';
export const GET_RUNS = '/api/monitors/runs/';
export const CREATE_JOB = '/api/monitors';
export const DELETE_JOB = '/api/monitors/';
export const UPDATE_JOB= '/api/monitors/';
export const GET_JOB= '/api/monitors/';
export const CREATE_PING = '/api/pings';
export const GET_SSE = '/api/sse';